= ALGUI
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: left
:toclevels: 5

**A**bstract **L**ua **G**raphical **U**ser **I**nterface is a Lua library which aims to be an embeddable, flexible and simple GUI system.

It depends on the https://github.com/ImagicTheCat/Luaoop[Luaoop] library.

TIP: If your GUI relies on time and you don't already have some kind of scheduler, https://github.com/ImagicTheCat/ELScheduler[ELScheduler] may interest you.

== Concepts

GUI:: root widget
Widget:: object which may contain other widgets
Renderer:: used to render a GUI

Widgets are 2D surfaces (rectangles) with an inner content.
The GUI or the widgets can be created/extended and multiple renderers can be created/extended for the same GUI; the GUI logic and rendering are separated.

NOTE: A widget may hold graphical data, but it should be a property of the widget, not of the renderer (to keep the separation clear). For example, a renderer could do a text rendering optimization by backing text in textures; this should not be owned by a widget.

This design allows the use of ALGUI in flexible ways; the logic stays in Lua and the rendering can be done by something else.

=== View

Each widget has a view surface based on its parent's view surface. The view is recomputed when needed and allows to only render visible widgets.

=== Inner content

Each widget has an inner content which contains its children. The parent widget has *zoom* and *shift* properties to scale/shift the display of the inner content.

NOTE: The inner shift is applied in inner space, not in the parent widget space.

=== Layout

GUI layouts in general may be simple or complex ways to achieve dynamic organization of widgets based on some rules. ALGUI's widgets have a fixed surface and there are no internal rules to change that, but widgets can implement the `updateLayout()` method to create layouts.

Layouts are updated recursively; when updating its layout, each widget can call `updateLayout()` on its children to request a specific size (if needed) and the children may update their layouts accordingly. This way, widgets are allowed to organize their children and set their own size based on their own layout.

NOTE: Layouts are updated when the widgets' size or content is updated.

CAUTION: Layouts are built from the shallowest to the deepest widgets; widgets shouldn't base their layout on the parent data.

WARNING: Wrongly designed layouts may cause an infinite loop.
