= ALGUI
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: left
:toclevels: 5

**A**bstract **L**ua **G**raphical **U**ser **I**nterface is a Lua library which aims to be a simple and embeddable GUI system.

It depends on the https://github.com/ImagicTheCat/Luaoop[Luaoop] library.

TIP: If your GUI relies on time and you don't already have some kind of scheduler, https://github.com/ImagicTheCat/ELScheduler[ELScheduler] may interest you.

.Principles
- The library should be a framework, not a full fledged GUI; it must be defined/extended to suit needs.
- It should decouple logic and rendering for clarity and flexibility. +
E.g. the logic may stay in Lua and the rendering could be done by something else.
- It should be flexible. +
E.g. the 2D surface of a widget is not necessarily expressed in pixels of a screen, it could be meters for a VR/3D surface.
- It should allow for both statefull and stateless renderers. +
E.g. for performance rendering data could be updated only when needed.

== Concepts

GUI:: Root widget.
Widget:: Object which may contain other widgets. Defines a 2D surface (axis-aligned rectangle) with an inner content.
Renderer:: Used to render a GUI.

=== Event

Events are emitted on widgets and are deferred through an event loop.

.Event handler callback
[source, lua]
----
-- Event handler.
-- callback(widget, event, ...)
--- widget: event target
--- event: event identifier (any indexable value)
--- ...: event arguments
----

=== View

Each widget has a view surface based on its parent's view surface. The view is recomputed when needed and allows to only render visible widgets.

=== Inner content

Each widget has an inner content which contains its children. The parent widget has *zoom* and *shift* properties to scale/shift the display of the inner content.

NOTE: The inner shift is applied in inner space, not in the parent widget space.

=== Layout

GUI layouts in general may be simple or complex ways to achieve dynamic organization of widgets based on some rules. ALGUI widgets have a fixed surface and there are no internal rules to change that, but widgets can implement layouts through the `updateLayout()` method.

Layouts are updated recursively; when updating its layout, each widget can call `updateLayout()` on its children to request a specific size (if needed) and the children may update their layouts accordingly. This way, widgets are allowed to organize their children and set their own size based on their own layout.

NOTE: Layouts are updated when the widgets' size or content is updated.

CAUTION: Layouts are built from the shallowest to the deepest widgets; widgets shouldn't base their layout on the parent data.

WARNING: Wrongly designed layouts may cause an infinite loop.
